/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OrderValidator,
  OrderValidatorInterface,
} from "../OrderValidator";

const _abi = [
  {
    inputs: [],
    name: "getChainId",
    outputs: [
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class OrderValidator__factory {
  static readonly abi = _abi;
  static createInterface(): OrderValidatorInterface {
    return new utils.Interface(_abi) as OrderValidatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OrderValidator {
    return new Contract(address, _abi, signerOrProvider) as OrderValidator;
  }
}
